# Generated by Django 5.1.4 on 2025-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=100)),
                ("itemPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("itemQuantity", models.PositiveIntegerField()),
                ("itemLocation", models.CharField(max_length=100)),
                ("itemPriceCurrency", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                (
                    "itemImage",
                    models.ImageField(blank=True, null=True, upload_to="item_images/"),
                ),
            ],
        ),
    ]
