# Generated by Django 5.1.4 on 2025-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricespotter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="itemPriceCurrency",
            field=models.CharField(default="CAD", max_length=100),
        ),
    ]
