# Generated by Django 5.1.4 on 2025-01-04 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricespotter", "0002_alter_item_itempricecurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="date",
            field=models.CharField(default=datetime.timezone, max_length=100),
        ),
    ]
