# Generated by Django 5.1.4 on 2025-01-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricespotter", "0003_alter_item_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="itemDescription",
            field=models.CharField(default="", max_length=9999),
        ),
        migrations.AlterField(
            model_name="item",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
