# Generated by Django 5.1.4 on 2025-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricespotter", "0004_user_item_itemdescription_alter_item_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
